### ISSUE TITLE
How to use it 

### ISSUE THREAD

**Issue by daeminjung** [vitorgalvao/download-media-workflow#1]
### Workflow version

2022.5

### Alfred version

5.0.6

### macOS version

13.2 (a) 

### Debugger output

```alfred_debugger
I tried to use the workflow by putting "dv name of the movie" in the Alfred search window but it didn't work.
```

### More details

![error #1](https://user-images.githubusercontent.com/121321798/209413453-43e53606-6179-4b66-8b26-2809be3eed61.jpeg)
![error #2](https://user-images.githubusercontent.com/121321798/209413457-5c64b564-dc24-4b1a-b9fc-4df4202e14cb.jpeg)

**Comment by vitorgalvao** [comment]
You don't search for a movie name, `dv` offers to download the URL in your clipboard or the frontmost tab. That is explained in the instructions in this repo, in the Gallery, and in the workflow itself.

**Comment by yarub123** [comment]
@vitorgalvao Just curious, how does the download playlist option work for a youtube playlist (for example my "Likes" playlist). When I do it, it creates a folder but only downloads one song.
