### ISSUE TITLE
How to add Firefox browser support?

### ISSUE THREAD

**Issue by yarub123** [vitorgalvao/download-media-workflow#4]
### Workflow version

2022.5

### Alfred version

5.0.6

### macOS version

13.1

### Debugger output

```alfred_debugger
Not a supported browser
```

### More details

I understand it's happening because it's not Chromium based. But is there anything I can do on my end to Firefox support?

No worries if too complicated. It's honestly not a big deal and don't use it a lot. 

Thanks anyways. Love the new update, looks very clean.

**Comment by vitorgalvao** [comment]
> is there anything I can do on my end to Firefox support?

Copy the link to your clipboard. `dv` and `da` support that as well and should tell you so in the subtitle.

> Love the new update, looks very clean.

Than you.
