### ISSUE TITLE
Not downloading anything anymore

### ISSUE THREAD

**Issue by yarub123** [vitorgalvao/download-media-workflow#6]
### Workflow version

2023.2

### Alfred version

5.1 (2131)

### macOS version

13.4.1 (c) Ventura

### Debugger output

```alfred_debugger
Tried it with Twitter videos as well as YouTube. Tried Audio and Video separately. Tried changing Audio format. Same error still 😞 Thanks in Advance though ❤️ 

Debug output in screenshot below.
```

### More details

<img width="525" alt="image" src="https://github.com/vitorgalvao/download-media-workflow/assets/84487964/941ab17a-a112-4daa-80e4-306f5ffc903b">

**Comment by vitorgalvao** [comment]
Use [Alfred’s Dependency Management](https://www.alfredapp.com/help/kb/dependencies/)  to ensure `yt-dlp` is up-to-date. That’s something which can only be fixed by their side.

**Comment by yarub123** [comment]
@vitorgalvao Much appreciated. Just for fun I updated it to 2023.3 before checking dependencies. And it worked. Though I'll still update the dependencies.
