### ISSUE TITLE
How to pass yt-dlp arguments? Such as "--embed-thumbnail"

### ISSUE THREAD

**Issue by LampPrinter** [vitorgalvao/download-media-workflow#7]
### Feature details

Like the title says. You can customise the title and advanced format. How to pass more arguments?

**Comment by vitorgalvao** [comment]
Arbitrary arguments are not a provided option. Those could conflict with everything else and would be hard to debug. For example, embedding thumbnails does not work with every format.

You can change the flags by editing the code in the workflow itself, but that isn’t supported and will be overwritten on workflow updates. However, the workflow has been quite stable for quite a while so updates haven’t been necessary.
